const middleware = require('./middleware');
const AuthenticationController = require('./controllers/AuthenticationController')
const AuthenticationControllerPolicy = require('./policies/AuthenticationControllerPolicy')
const CursoController = require('./controllers/CursoController')
const ModuloController = require('./controllers/ModuloController')
const AulaController = require('./controllers/AulaController')
const LogController = require('./controllers/LogController')
const AuditoriaController = require('./controllers/AuditoriaController')
const AulaUsuarioController = require('./controllers/AulaUsuarioController')
const AssinaturaController = require('./controllers/AssinaturaController')
const ComentarioAulaController = require('./controllers/ComentarioAulaController')
const CursoAssinaturaController = require('./controllers/CursoAssinaturaController')
const UsuarioAssinaturaController = require('./controllers/UsuarioAssinaturaController')
const UsuarioCursoController = require('./controllers/UsuarioCursoController')

module.exports = (app) => {
  app.post('/register', AuthenticationControllerPolicy.register, AuthenticationController.register)
  app.post('/newUser', AuthenticationController.new)
  app.post('/login', AuthenticationController.login)
  app.put('/changePassword', AuthenticationControllerPolicy.changePassword, AuthenticationController.changePassword)
  app.put('/user/:userId', middleware.checkToken, AuthenticationController.put)
  app.get('/user/:userId', middleware.checkToken, AuthenticationController.show)
  app.get('/usersView', middleware.checkToken, AuthenticationController.view)
  app.put('/userPermission/:userId', middleware.checkToken, AuthenticationController.permission)
  app.get('/users', middleware.checkToken, AuthenticationController.index)
  app.get('/cursos', middleware.checkToken, CursoController.index)
  app.get('/cursosView', middleware.checkToken, CursoController.view)
  app.post('/curso', middleware.checkToken, CursoController.post)
  app.get('/curso/:cursoId', middleware.checkToken, CursoController.show)
  app.put('/curso/:cursoId', middleware.checkToken, CursoController.put)
  app.delete('/curso/:cursoId', middleware.checkToken, CursoController.delete)
  app.get('/modulos/:cursoId', middleware.checkToken, ModuloController.index)
  app.get('/modulosView/:cursoId', middleware.checkToken, ModuloController.view)
  app.post('/modulo', middleware.checkToken, ModuloController.post)
  app.get('/modulo/:moduloId', middleware.checkToken, ModuloController.show)
  app.put('/modulo/:moduloId', middleware.checkToken, ModuloController.put)
  app.delete('/modulo/:moduloId', middleware.checkToken, ModuloController.delete)
  app.get('/aulas/:moduloId', middleware.checkToken, AulaController.index)
  app.get('/aulasView/:moduloId', middleware.checkToken, AulaController.view)
  app.post('/aula', middleware.checkToken, AulaController.post)
  app.get('/aula/:aulaId', middleware.checkToken, AulaController.show)
  app.put('/aula/:aulaId', middleware.checkToken, AulaController.put)
  app.delete('/aula/:aulaId', middleware.checkToken, AulaController.delete)
  app.get('/logView', middleware.checkToken, LogController.view)
  app.get('/log/:logId', middleware.checkToken, LogController.show)
  app.get('/auditoriaView', middleware.checkToken, AuditoriaController.view)
  app.get('/auditoria/:auditoriaId', middleware.checkToken, AuditoriaController.show)
  app.get('/auditoriaViewQ', async function(req, res) {
    AuditoriaController.viewQ(req, res)
      .then((response) => {
        res.status(response.status).json(response.message)
      }).catch((error) => {
        res.status(error.status).json(error.message);
      })
  })
  app.get('/aulaUsuarios', middleware.checkToken, AulaUsuarioController.view)  
  app.post('/aulaUsuario', middleware.checkToken, AulaUsuarioController.upsert)  
  app.get('/aulaUsuario/:aulaId/:userId', middleware.checkToken, AulaUsuarioController.show)  
  app.get('/aulaUsuarioMedia/:aulaId', middleware.checkToken, AulaUsuarioController.showMedia)  
  app.get('/assinaturas', middleware.checkToken, AssinaturaController.view)
  app.post('/assinatura', middleware.checkToken, AssinaturaController.post)
  app.get('/assinatura/:assinaturaId', middleware.checkToken, AssinaturaController.show)
  app.put('/assinatura/:assinaturaId', middleware.checkToken, AssinaturaController.put)
  app.delete('/assinatura/:assinaturaId', middleware.checkToken, AssinaturaController.delete)
  app.get('/comentarioAula/:aulaId', middleware.checkToken, ComentarioAulaController.view)  
  app.post('/comentarioAula', middleware.checkToken, ComentarioAulaController.post)  
  app.put('/comentarioAula/:comentarioId', middleware.checkToken, ComentarioAulaController.put)  
  app.delete('/comentarioAula/:comentarioId', middleware.checkToken, ComentarioAulaController.delete)  
  app.get('/cursoAssinatura/:assinaturaId', middleware.checkToken, CursoAssinaturaController.view)  
  app.post('/cursoAssinatura', middleware.checkToken, CursoAssinaturaController.post)  
  app.delete('/cursoAssinatura/:cursoId/:assinaturaId', middleware.checkToken, CursoAssinaturaController.delete)  
  app.get('/usuarioAssinatura/:userId', middleware.checkToken, UsuarioAssinaturaController.show)  
  app.post('/usuarioAssinatura', middleware.checkToken, UsuarioAssinaturaController.post)  
  app.delete('/usuarioAssinatura/:userId/:assinaturaId', middleware.checkToken, UsuarioAssinaturaController.delete)  
  app.get('/assinaturasToken', middleware.checkToken, AssinaturaController.view)
  app.get('/cursosAssinaturaView/:userId', middleware.checkToken, CursoController.viewCursosAssinatura)
  app.post('/geraCertificado/:userId/:cursoId', UsuarioCursoController.geraCertificado)
  app.get('/validaCertificado/:desHash', UsuarioCursoController.validaCertificado)
}
