const AuthenticationController = require('./controllers/AuthenticationController')
const AuthenticationControllerPolicy = require('./policies/AuthenticationControllerPolicy')
const CursoController = require('./controllers/CursoController')
const ModuloController = require('./controllers/ModuloController')
const AulaController = require('./controllers/AulaController')

module.exports = (app) => {
  app.post('/register', AuthenticationControllerPolicy.register, AuthenticationController.register)
  app.post('/newUser', AuthenticationController.new)
  app.post('/login', AuthenticationController.login)
  app.put('/user/:userId', AuthenticationController.put)
  app.get('/user/:userId', AuthenticationController.show)
  app.get('/users', AuthenticationController.index)
  app.get('/curso', CursoController.index)
  app.post('/curso', CursoController.post)
  app.get('/curso/:cursoId', CursoController.show)
  app.put('/curso/:cursoId', CursoController.put)
  app.delete('/curso/:cursoId', CursoController.delete)
  app.get('/modulos/:cursoId', ModuloController.index)
  app.post('/modulo', ModuloController.post)
  app.get('/modulo/:moduloId', ModuloController.show)
  app.put('/modulo/:moduloId', ModuloController.put)
  app.delete('/modulo/:moduloId', ModuloController.delete)
  app.get('/aulas/:moduloId', AulaController.index)
  app.post('/aula', AulaController.post)
  app.get('/aula/:aulaId', AulaController.show)
  app.put('/aula/:aulaId', AulaController.put)
  app.delete('/aula/:aulaId', AulaController.delete)
}
